version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: inhouse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inhouse
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - inhouse-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  inhouse-mysql-data:
